version: "3.3"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_DB
    ports:
      - "1433:1433"
    environment:
      "ACCEPT_EULA": "Y"
      "SA_PASSWORD": "MGG2hZPxtW22@"

  api:
    build:
      context: .
      dockerfile: Dockerfile_Api
    ports:
      - "2080:80"
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./storage_external:/app/default_storage
    environment:
      "Database:ConnectionString": "Data Source=192.168.222.104;Initial Catalog=HBKStorage;Persist Security Info=True;User ID=sa;Password=MGG2hZPxtW22@"
      "DefaultStorageProvider:EnsureCreated": "true"
      "DefaultStorageProvider:Location": "/app/default_storage"
      "DefaultStorageProvider:SizeLimit": "5368709120"
      "NLog:LogstashUrl": "http://192.168.222.102:5046/dev-hbk-storage-api"

  web:
    build:
      context: .
      dockerfile: Dockerfile_Web
    depends_on:
      - api
    ports:
      - "1080:80"
    environment:
      "HBKStorageUrl": "http://192.168.222.104:2080/"

  sync:
    build:
      context: .
      dockerfile: Dockerfile_Sync
    depends_on:
      - db
    environment:
      "Database:ConnectionString": "Data Source=192.168.222.104;Initial Catalog=HBKStorage;Persist Security Info=True;User ID=sa;Password=MGG2hZPxtW22@"
      "NLog:LogstashUrl": "http://192.168.222.102:5046/dev-hbk-storage-sync"