version: "3.3"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_DB
    ports:
      - "1433:1433"

  api:
    build:
      context: .
      dockerfile: Dockerfile_Api
    ports:
      - "2080:80"
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./storage_external:/app/default_storage
    environment:
      "Database:ConnectionString": "Data Source=db;Initial Catalog=db;Persist Security Info=True;User ID=sa;Password=MGG2hZPxtW22@"
      "DefaultStorageProvider:EnsureCreated": "true"
      "DefaultStorageProvider:Location": "/app/default_storage"
      "DefaultStorageProvider:SizeLimit": "5368709120"
      "RootKey:Key": "ThisIsKeyForRoot_60990e6c-95f2-412e-8708-1961777e88fc"
      "NLog:LogstashMinLevel": "Off"

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile_Dashboard
    depends_on:
      - api
    ports:
      - "1080:80"
    environment:
      "HBKStorageUrl": "http://localhost:2080"

  sync:
    build:
      context: .
      dockerfile: Dockerfile_Sync
    depends_on:
      - db
    volumes:
      - ./storage_external:/app/default_storage
    environment:
      "Database:ConnectionString": "Data Source=db;Initial Catalog=HBKStorage;Persist Security Info=True;User ID=sa;Password=MGG2hZPxtW22@"
      "NLog:LogstashMinLevel": "Off"
  
  image_compress_plugin:
    build:
      context: .
      dockerfile: Dockerfile_ImageCompressPlugin
    depends_on:
      - db
    volumes:
      - ./storage_external:/app/default_storage
    environment:
      "Database:ConnectionString": "Data Source=db;Initial Catalog=HBKStorage;Persist Security Info=True;User ID=sa;Password=MGG2hZPxtW22@"
      "NLog:LogstashMinLevel": "Off"
      "ImageCompressTaskOptions:IsExecuteOnLocalStorage": "True"