version: "3.3"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_DB
    ports:
      - "1433:1433"

  api:
    build:
      context: .
      dockerfile: Dockerfile_Api
    ports:
      - "2080:80"
    restart: unless-stopped
    depends_on:
      - db
    environment:
      "Database:ConnectionString": "Data Source=192.168.222.104;Initial Catalog=HBKStorage;Persist Security Info=True;User ID=sa;Password=MGG2hZPxtW22@"

  web:
    build:
      context: .
      dockerfile: Dockerfile_Web
    depends_on:
      - api
    ports:
      - "1080:80"
    environment:
      "HBKStorageUrl": "http://192.168.222.104:2080"

  sync:
    build:
      context: .
      dockerfile: Dockerfile_Sync
    depends_on:
      - db
    environment:
      "Database:ConnectionString": "Data Source=192.168.222.104;Initial Catalog=HBKStorage;Persist Security Info=True;User ID=sa;Password=MGG2hZPxtW22@"