FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "HBK.Storage.ImageCompressPlugin/HBK.Storage.ImageCompressPlugin.csproj"
WORKDIR "/src/HBK.Storage.ImageCompressPlugin"
RUN dotnet build "HBK.Storage.ImageCompressPlugin.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "HBK.Storage.ImageCompressPlugin.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "HBK.Storage.ImageCompressPlugin.dll"]