version: "3.3"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_DB
    ports:
      - "1433:1433"

  api:
    build:
      context: .
      dockerfile: Dockerfile_Api
    ports:
      - "2080:80"
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./storage_external:/app/default_storage
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "Database:ConnectionString": "Data Source=192.168.222.104;Initial Catalog=HBKStorage;Persist Security Info=True;User ID=sa;Password=MGG2hZPxtW22@"
      "DefaultStorageProvider:EnsureCreated": "true"
      "DefaultStorageProvider:Location": "/app/default_storage"
      "DefaultStorageProvider:SizeLimit": "5368709120"
      "RootKey:Key": "ThisIsKeyForRoot_60990e6c-95f2-412e-8708-1961777e88fc"
      "NLog:LogstashUrl": "http://192.168.222.102:5046/dev-hbk-storage-api"
      "NLog:LogstashMinLevel": "Trace"

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile_Dashboard
    depends_on:
      - api
    ports:
      - "1080:80"
    environment:
      "HBKStorageUrl": "https://dev-sapi.night-soul.com/"

  sync:
    build:
      context: .
      dockerfile: Dockerfile_Sync
    depends_on:
      - db
    volumes:
      - ./storage_external:/app/default_storage
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "Database:ConnectionString": "Data Source=192.168.222.104;Initial Catalog=HBKStorage;Persist Security Info=True;User ID=sa;Password=MGG2hZPxtW22@"
      "NLog:LogstashUrl": "http://192.168.222.102:5046/dev-hbk-storage-sync"
      "NLog:LogstashMinLevel": "Trace"
  
  image_compress_plugin:
    build:
      context: .
      dockerfile: Dockerfile_ImageCompressPlugin
    depends_on:
      - db
    volumes:
      - ./storage_external:/app/default_storage
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "Database:ConnectionString": "Data Source=192.168.222.104;Initial Catalog=HBKStorage;Persist Security Info=True;User ID=sa;Password=MGG2hZPxtW22@"
      "NLog:LogstashUrl": "http://192.168.222.102:5046/dev-hbk-storage-image-compress-plugin"
      "NLog:LogstashMinLevel": "Trace"
      "ImageCompressTaskOptions:IsExecuteOnLocalStorage": "True"