// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using HBK.Storage.Adapter.DataAnnotations;
using HBK.Storage.Adapter.Enums;
using HBK.Storage.Adapter.Interfaces;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace HBK.Storage.Adapter.Storages
{
    /// <summary>
    /// 儲存服務
    /// </summary>
    public partial class StorageProvider : ITimeStampModel, ISoftDeleteModel
    {
        /// <summary>
        /// 建構一個新的執行個體
        /// </summary>
        public StorageProvider()
        {
            this.AuthorizeKeyScope = new HashSet<AuthorizeKeyScope>();
            this.StorageGroup = new HashSet<StorageGroup>();
            this.FileAccessToken = new HashSet<FileAccessToken>();
        }
        /// <summary>
        /// 取得或設定儲存服務 ID
        /// </summary>
        [Key]
        [Column("StorageProviderID")]
        public Guid StorageProviderId { get; set; }
        /// <summary>
        /// 取得或設定儲存服務流水號
        /// </summary>
        public long StorageProviderNo { get; set; }
        /// <summary>
        /// 取得或設定名稱
        /// </summary>
        [Required]
        [StringLength(255)]
        [Sortable]
        [Filterable]
        public string Name { get; set; }
        /// <summary>
        /// 取得建立時間
        /// </summary>
        [Sortable]
        public DateTimeOffset CreateDateTime { get; internal set; }
        /// <summary>
        /// 取得最後更新時間
        /// </summary>
        public DateTimeOffset? UpdateDateTime { get; internal set; }
        /// <summary>
        /// 取得刪除時間
        /// </summary>
        public DateTimeOffset? DeleteDateTime { get; internal set; }
        /// <summary>
        /// 取得或設定狀態
        /// </summary>
        public StorageProviderStatusEnum Status { get; set; }

        /// <summary>
        /// 取得或設定金鑰使用範圍集合
        /// </summary>
        [InverseProperty("StorageProvider")]
        public virtual ICollection<AuthorizeKeyScope> AuthorizeKeyScope { get; set; }
        /// <summary>
        /// 取得或設定擁有儲存群組集合
        /// </summary>
        [InverseProperty("StorageProvider")]
        public virtual ICollection<StorageGroup> StorageGroup { get; set; }
        /// <summary>
        /// 取得或設定檔案存取權杖集合
        /// </summary>
        [InverseProperty("StorageProvider")]
        public virtual ICollection<FileAccessToken> FileAccessToken { get; set; }
        DateTimeOffset? ITimeStampModel.UpdateDateTime { get => this.UpdateDateTime; set => this.UpdateDateTime = value; }
        DateTimeOffset ICreatedDateModel.CreateDateTime { get => this.CreateDateTime; set => this.CreateDateTime = value; }
        DateTimeOffset? ISoftDeleteModel.DeleteDateTime { get => this.DeleteDateTime; set => this.DeleteDateTime = value; }
    }
}